#基础配置
server:
  port: 80
spring:
  application:
    name: zuul-server
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    config: # 配置中心
      label: master
      name: zuul
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
## Eureka配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3  # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-expiration-duration-in-seconds: 5  # eureka 举例最近的一次心跳等待提出的时间，默认90s

#给服务器配置路由
zuul:
  sensitiveHeaders: "*"   #设置为 * 表示不过滤任何敏感头
  routes:
    member-server:
      path: /memberapi/**
      serviceId: member-server
    goods-server:
      path: /goodsapi/**
    cart-server:
      path: /cartapi/**
    order-server:
      path: /orderapi/**
    defulatPath:
      path: /**
      serviceId: index-server
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000


# 配置动态刷新git配置的路径终端请求地址
management:
  endpoints:
    web:
      exposure:
        include: refresh
