server:
  port: 8000

spring:
  application:
    name: index-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#  mvc:
#    static-path-pattern: /static/**

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# mybatis sql日志
logging:
  level:
    org.springframework: info
    com.fresh.member.mapper: debug
