server:
  port: 8000

spring:
  application:
    name: index-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
