server:
  port: 8003
spring:
  application:
    name: member-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  redis:
    host: 127.0.0.1
    port: 6379
  # 数据库连接池配置 druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fresh?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 18374809932
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000

# mybatis 配置
mybatis:
  type-aliases-package: com.fresh.common.entity    # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

# mybatis sql日志
logging:
  level:
    com.fresh.member.mapper: debug








eureka:
  instance:
    lease-renewal-interval-in-seconds: 1  # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-expiration-duration-in-seconds: 2  # eureka 举例最近的一次心跳等待提出的时间，默认90s

ribbon:
  ConnectTimeout: 15000          # 创建连接的超时时间，单位：ms
  ReadTimeout: 10000             # 在连接创建好以后，调用接口的超时时间，单位：ms
  SocketTimeout: 10000

feign:
  hystrix:
    enabled: true #打开feign客户端的内置hystrix

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000