server:
  port: 8002
spring:
  application:
    name: goods-server
  redis:
    host: 127.0.0.1
    port: 6379
  # 数据库连接池配置 druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fresh?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
# mybatis 配置
mybatis:
  type-aliases-package: com.fresh.common.entity    # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

# mybatis sql日志
logging:
  level:
    com.yc.goods.mapper: debug




#lcn事务管理器ip端口
tx-lcn:
  client:
    manager-address: 127.0.0.1:5800
#  ribbon:
#    loadbalancer:
#      dtx:
#        enabled: true #是否采用轮训

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1  # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-expiration-duration-in-seconds: 2  # eureka 举例最近的一次心跳等待提出的时间，默认90s


# 配置hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000   # 设置hystrix超时时间，超过2秒触发降级
      circuitBreaker: # 配置断路器
        enabled: true